# server
server: 
  port: 81

# database数据源配置
spring:
    datasource:
        name: spring-boot-mybatis
        url: jdbc:mysql://192.168.25.201:3306/seckill
        username: root
        password: root9918
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
# redis config
    redis:
      host: 192.168.25.111
      port: 6379
      password: 
      pool:
       max-idle: 100
       min-idle: 1
       max-active: 1000
       max-wait: -1
# mybatis映射文件存放位置
mybatis:
  mapper-locations: classpath:mapping/*.xml

# pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

