
# 内置tomcat配置，参考https://blog.csdn.net/mn960mn/article/details/51306140
server: 
  port: 8080
  tomcat: 
    max-threads: 2000
  
  
spring: 
# thymeleaf
  thymeleaf: 
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
# datasource
  datasource:
    name: spring-boot-mybatis
    url: jdbc:mysql://192.168.25.201:3306/miaosha
    username: root
    password: root9918
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 1000
    initialSize: 100
    maxWait: 60000
    minIdle: 500
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
# redis config
  redis:
    host: 192.168.25.201
    port: 6379
    password: 
    timeout: 500000 ## 关键
    pool:
     max-idle: 500
     min-idle: 50
     max-active: 3000
     max-wait: 100000
# redis, spring-boot集成redis有一种比较简单的方式, 参考https://github.com/HMDOBO/spring-boot/tree/master/spring-boot-cache-redis
# 但是这里为了一致性, 采用了自己实现redisTemplate的方式, 而不用spring-redis-Template包
#redis:
#  host: 192.168.25.111
#  port: 6379
#  timeout: 10
#  password: 
#  poolMaxTotal: 1000
#  poolMaxIdle: 500
#  poolMaxWait: 500

# rabbitmq
  rabbitmq: 
    host: 192.168.25.201
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener: 
      concurrency: 10 # 消费者数量
      max-concurrency: 10 # 消费者最大数量
      prefetch: 1 # 消费者每次从队列中取几个消息
      auto-startup: true # 启动时自动启动消费者
      default-requeue-rejected: true # 消息消费失败后，重新进入消费队列中
      retry:
        enabled: true # 启用发布重试
        initial-interval: 1000 # 1秒后重试
        max-attempts: 3 # 传递消息的最大尝试次数
        max-interval: 10000 # 尝试的最大时间间隔
        multiplier: 1.0 # 应用于先前传递重试时间间隔的乘数
      

# mybatis
mybatis:
  mapper-locations: classpath:mapping/*.xml


